version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:example@postgres/innserver
      APP_CLIENT_URL: vkjvhjscvkjsd
      SECRET_REF_JWT: ksdhf
  postgres:
    image: postgres:14.2-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: innserver
      POSTGRES_PASSWORD: example
